### ISSUE TITLE
[🐛 Bug]: Sometimes calling metamask.confirmPermissionToApproveAll() method on Metamask approve window is failing using Playwright + Synpress as plugin

### ISSUE THREAD

**Issue by DavitMkhitaryan** [Synthetixio/synpress#1047]
### 🔎 Have you searched existing issues to avoid duplicates?

- [X] I have made sure that my issue is not a duplicate.

### 🧪 Have you tested your code using latest version of Synpress?

- [X] I have made sure that my issue still exists on [latest version of Synpress](https://github.com/Synthetixio/synpress/releases).

### 💡 Are you able to provide enough information to be able to reproduce your issue locally?

- [X] I can provide enough details to reproduce my issue on local environment.

### Synpress version

^3.7.2-beta.9

### Node.js version

v18.16.0

### Operating system

macOS Sonoma 14.0

### Run mode

Playwright + Synpress (as plugin)

### Are you running your tests inside docker? (if applicable)

- [ ] This issue could be related to docker.

### What happened?

metamask.confirmPermissionToApproveAll() method is failing. Inside my test, I opened approve tokens Metamask window and called method confirmPermissionToApproveAll() to approve all. Running in headed mode, I see that the approve is successful, metamask window is closed, however the method itself fails and fails my test because it is expecting some locator after approval is successful. Below providing, the error logs referring to the synpress library.

Logs:

```
Error: page.waitForSelector: Target page, context or browser has been closed
    Call log:
      - waiting for locator('.notification .set-approval-for-all-warning__footer__approve-button') to be visible


       at ../pages/---.page.ts:493

    > 493 |     await metamask.confirmPermissionToApproveAll();


        at Object.waitFor (/Users/---/---/---/---/node_modules/@synthetixio/synpress/commands/playwright.js:203:16)
        at Object.waitAndClick (/Users/---/---/---/---/node_modules/@synthetixio/synpress/commands/playwright.js:217:21)
        at Object.confirmPermissionToApproveAll (/Users//---/---/---/---/node_modules/@synthetixio/synpress/commands/metamask.js:1371:5)
```

### How to reproduce the bug.

To reproduce the bug, just call metamask.confirmPermissionToApproveAll() method in any autotest on Metamask approval window. I'm using Metamask version "10.25.0"

**Comment by duckception** [comment]
Hey! You're using an incorrect function here 😅 For token approvals, you should be using `confirmMetamaskPermissionToSpend`. The `confirmPermissionToApproveAll` function is meant for NFT all approvals. Sorry for the confusion, I know this is a bit messy. The upcoming version of Synpress will have a simpler and more intuitive API 🫡

Please, let me know if it helps 🙏

**Comment by duckception** [comment]
My bad, I've copied it over from our Cypress tests that have this additional `Metamask` word in it.
