### ISSUE TITLE
[🐛 Bug]: Importing Playwright inside Cypress utils

### ISSUE THREAD

**Issue by re2005** [Synthetixio/synpress#1237]
### 🔎 Have you searched existing issues to avoid duplicates?

- [X] I have made sure that my issue is not a duplicate.

### 🧪 Have you tested your code using latest version of Synpress?

- [X] I have made sure that my issue still exists on [latest version of Synpress](https://github.com/Synthetixio/synpress/releases).

### 💡 Are you able to provide enough information to be able to reproduce your issue locally?

- [X] I can provide enough details to reproduce my issue on local environment.

### Synpress version

4.0.x

### Node.js version

21

### Operating system

macOS 15.0.1

### Run mode

Cypress + Synpress (as plugin)

### Are you running your tests inside docker? (if applicable)

- [ ] This issue could be related to docker.

### What happened?

In the cypress utils you are importing Playwright stuff

https://github.com/Synthetixio/synpress/blob/dev/wallets/ethereum-wallet-mock/src/cypress/utils/initEthereumWalletMock.ts#L2

### What is your expected behavior?

Not have dependency on Playwright when I'm using Cypress

### How to reproduce the bug.

Try using the plugin with cypress

**Comment by re2005** [comment]
It works if you also install 

`yarn add @playwright/test typescript`

**Comment by localtechboy** [comment]
@re2005 It's not a mistake. We want to import Playwright feature to be able to connect to a running browser. Also I can see both dependencies are properly listed in the package.json:
https://github.com/Synthetixio/synpress/blob/dev/wallets/ethereum-wallet-mock/package.json
