### ISSUE TITLE
axios get 403 error when runing

### ISSUE THREAD

**Issue by joemaoniu** [Synthetixio/synpress#138]
https://user-images.githubusercontent.com/83738283/117539345-ca178f00-b03c-11eb-81b7-8d176344ae3f.mov

my issue happens when i try to run a specific spec, then I got an 403 error, The issue seems coming from line 50 this file
https://github.com/Synthetixio/synpress/blob/master/helpers.js

**Comment by drptbl** [comment]
@joemaoniu Hey, does it still occur?

Have you followed README, "important" section?
https://github.com/Synthetixio/synpress#-important

```
Metamask version is hardcoded and frequently updated under supervision to avoid a case when e2e tests break because of CSS classes changes in new version, so all you need is to keep synpress updated in your project. However, you can still override metamask with METAMASK_VERSION environmental variable, for example: METAMASK_VERSION=9.3.0 or METAMASK_VERSION=latest.
```

**Comment by drptbl** [comment]
@joemaoniu let me know if this still happens, thanks!
