### ISSUE TITLE
Standalone version that doesn't ship Cypress and can be integrated into any setup.

### ISSUE THREAD

**Issue by carlos0202** [Synthetixio/synpress#153]
Thanks for the good work with this wrapper. I was trying to use it and ran into some issues:

- How can we extend our cypress setup by adding custom commands and other trivial things if the library is abstracting away the cypress commands and plugins file?
- How can we use it in a typescript project with tests written in typescript?
- Is there any better way to set up everything (especially the part of the eslint.js file)?
Thanks in advance for your help!!!

**Comment by drptbl** [comment]
Hey @carlos0202,
1. Currently there is no easy way to do it. I will think about it in future. You have to fork the repository and add your own custom commands this way.
2. Sadly, I had no chance to test it out with Typescript project yet, so I can't really assist you here at current moment, sorry.
3. Not at current state of synpress. It's still very early in development and being solely developed by me, it needs some time to mature.

**Comment by drptbl** [comment]
@carlos0202 Let me know if you have any other questions/feedback.

Cheers,
Jakub.
