### ISSUE TITLE
Stuck on metamask window when using a custom network

### ISSUE THREAD

**Issue by ola-jha** [Synthetixio/synpress#154]
Hi thanks for this really cool tool. I have a couple of issues here. Main issue is that when I enter a custom network, the screen stays stuck on metamask screen and times out. It works fine when I use one of the pre installed networks.

I also wanted to ask if there was an easy way to add more configuration without changing it in the node modules. For example, more custom commands or events (ex. on, uncaught:error)

**Comment by drptbl** [comment]
Hey @ola-jha, thanks for good words. I will take a closer look on custom network feature over the weekend and report back to you.

Sadly, there is no easy way to extend synpress functionality easily at the moment. I will consider this for future.

Cheers,
Jakub.

**Comment by ola-jha** [comment]
@drptbl I actually found the issue. My string had spaces in it. It worked when it had no spaces.

**Comment by drptbl** [comment]
@ola-jha thanks for feedback! let me know if you have any other issues, happy to help.

Cheers,
Jakub.
