### ISSUE TITLE
Error at confirmMetamaskTrancsaction

### ISSUE THREAD

**Issue by borbier** [Synthetixio/synpress#185]
I've tried using the module for testing, the processes such as set up wallet is ok. However, I've found the error on confirm a transaction, here is the prompt shown in Cypress.

```
  at <unknown> (__puppeteer_evaluation_script__:1:64)
  at <unknown> (__puppeteer_evaluation_script__:1:64)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:142397:20)
From previous event:
    at Context.task (http://localhost:3000/__cypress/runner/cypress_runner.js:142379:16)
From Your Spec Code:

From Node.js Internals:
    Error: Evaluation failed: ReferenceError: _this is not defined
      at <unknown> (__puppeteer_evaluation_script__:1:64)
```

I've tried searching for workaround in Puppeteer but there is no clue in this case.

**Comment by drptbl** [comment]
Hey @borbier, thanks for reporting and sorry for delay (was taking some vacations).

I will take a look in to it tomorrow, cheers!

**Comment by drptbl** [comment]
Hey @borbier, sorry for delay.

It works just fine in my case:
<img width="1200" alt="Screenshot 2021-08-18 at 11 35 22" src="https://user-images.githubusercontent.com/8177587/129875644-28e7b766-5eed-4eb1-a13d-c22bada093df.png">

You can refer to kwenta repository to see an example:
https://github.com/Synthetixio/kwenta/tree/fix-e2e/tests/e2e

Let me know if you have any more issues.

Thanks,
Jakub.
