### ISSUE TITLE
Why am i socket hang up or ETIMEDOUT?

### ISSUE THREAD

**Issue by lpf763827726** [Synthetixio/synpress#208]
i havn't change anything, and the test file are almost empty, but always socket hang up or ETIMEDOUT?

![2021-08-27_17-40](https://user-images.githubusercontent.com/43004977/131203146-fbb29acc-e7fc-43a7-b018-03d3edd75e95.png)
![2021-08-28_09-39](https://user-images.githubusercontent.com/43004977/131203148-20809894-31e6-4915-b9de-84652746ad73.png)
![2021-08-28_09-39_1](https://user-images.githubusercontent.com/43004977/131203149-feac10de-b4dd-4d71-8dcb-486ccb329dd5.png)
![2021-08-28_09-39_2](https://user-images.githubusercontent.com/43004977/131203150-e7602bca-f38b-4dd2-95f0-06603b4be9ce.png)
![2021-08-28_10-17](https://user-images.githubusercontent.com/43004977/131203154-758589bb-a1e9-4f5f-acec-660b34186b94.png)

please help me, thanks, i don't know how to let it work

**Comment by lpf763827726** [comment]
when i run any test, it always starts for a long time

**Comment by drptbl** [comment]
Sorry but you're not following the readme. That's the main reason of your errors.

**Comment by lpf763827726** [comment]
i try to follow the readme, but when i run `npm run syncress:run` it will err:
```
Timed out waiting for the browser to connect. Retrying...

Timed out waiting for the browser to connect. Retrying again...

The browser never connected. Something is wrong. The tests cannot run. Aborting...

The browser never connected. Something is wrong. The tests cannot run. Aborting...
Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (/home/sp2/.cache/Cypress/8.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/home/sp2/.cache/Cypress/8.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)


  (Results)
```

my synpress:run is `synpress run --configFile tests/e2e/customConfig.json`

customConfig.json:
```
{
    "retries": { "runMode": 0, "openMode": 0 },
    "integrationFolder": "tests/e2e/specs",
    "screenshotsFolder": "tests/e2e/screenshots",
    "videosFolder": "tests/e2e/videos",
    "chromeWebSecurity": true,
    "viewportWidth": 1366,
    "viewportHeight": 768,
    "component": {
        "componentFolder": ".",
        "testFiles": "**/*spec.{js,jsx,ts,tsx}"
    },
    "env": {
        "SECRET_WORDS": "hockey, envelope, panel, gun, mouse, almost, village, fat, announce, vanish, erode, service",
        "NETWORK_NAME": "goerli",
        "PASSWORD": "11111111",
        "coverage": false
    },
    "defaultCommandTimeout": 30000,
    "pageLoadTimeout": 30000,
    "requestTimeout": 30000
}
```

i use `run` always timeout, but i use `open`, i have 30% can open the test(but it need so long time)
