### ISSUE TITLE
Cannot run in docker with Xvfb installed

### ISSUE THREAD

**Issue by shawnwang0715** [Synthetixio/synpress#215]
I found some behaviors are weird and make this can't run in docker.

1. In this line: https://github.com/Synthetixio/synpress/blob/b9c2f3fdb7bb701fe190efe2099349e489d3d8e3/commands/puppeteer.js#L38
It detects whether the URL contains `integration`, however, Cypress seems doesn't have `__/#/tests/integration` suffix when running in docker, and this makes this detection failed.

2. I don't know why but I get stuck in this line when running with docker:  
https://github.com/Synthetixio/synpress/blob/b9c2f3fdb7bb701fe190efe2099349e489d3d8e3/commands/metamask.js#L228-L230 
It always shows timeout, and because I don't know how to see the video playback of the extension page, I don't know what happened there.

Thanks!

**Comment by shawnwang0715** [comment]
I think I was confused: is docker with Xvfb headed or headless? I know this package doesn't support headless mode but I'm not sure whether Xvfb is headed or headless.

**Comment by drptbl** [comment]
@shawnwang0715 you can use this docker image as a reference:
https://github.com/Synthetixio/docker-e2e

as per readme, you need xvfb in docker container because synpress runs only in headed mode.

both of the issues you've mentioned above shouldn't be a case with proper setup.

1) this url indeed exists and it shouldn't be an issue
2) probably related to missing xvfb inside docker container

**Comment by drptbl** [comment]
Hey, I'm closing this issue as it's not technical issue with synpress itself. Let me know if you need any more help.

Thanks,
Jakub.

**Comment by shawnwang0715** [comment]
Thanks for your reply, I tried to run synpress with a docker image `cypress/base:14.17.0` and it works too. So it must be something wrong with my previous environment.

**Comment by drptbl** [comment]
@shawnwang0715 glad to hear you've figured it out 🎉. Thanks for feedback! 🙏
