### ISSUE TITLE
Need a extra commands for confirming sign message on metamask

### ISSUE THREAD

**Issue by RabbitTerra** [Synthetixio/synpress#234]
![image](https://user-images.githubusercontent.com/83789292/136905763-9c2ba52e-53e8-4d37-8862-e559b4a427d7.png)

Hi, @drptbl. I'm having a trouble with confirming this personal sign and `eth_signTypedData_v4` request metamask popup.
I can't find proper command from the package.
Do you have an any idea for this?
Regards

**Comment by drptbl** [comment]
Hey @RabbitTerra,

There are commands for it:
https://github.com/Synthetixio/synpress/blob/dev/support/index.d.ts#L109-L120

You can use:
`cy.confirmMetamaskSignatureRequest();`
or
`cy.rejectMetamaskSignatureRequest();`

They have not been released as "production" release yet. If you want to use them, bump your `synpress` version to `0.9.25-beta.12` in `package.json`.

**Comment by RabbitTerra** [comment]
Hi, @drptbl . Thanks for your fast reply.
The command is working well.
Thank you very much for your support.
