### ISSUE TITLE
Need help for change accounts on metamask

### ISSUE THREAD

**Issue by RabbitTerra** [Synthetixio/synpress#237]
Hi, @drptbl.
Is there any method for changing accounts on metamask?

**Comment by drptbl** [comment]
Hey @RabbitTerra,

Yes, it's possible now :).

1. `cy.switchMetamaskAccount(accountNumber)`, for example: `cy.switchMetamaskAccount(2)`:
<img width="361" alt="Screenshot 2021-10-13 at 21 28 39" src="https://user-images.githubusercontent.com/8177587/137200560-36ffaa64-8df1-436a-abbf-63b4b2e9c2f3.png">
2.`cy.switchMetamaskAccount('accountName')`, for example: `cy.switchMetamaskAccount('Account 2')`

More details:
https://github.com/Synthetixio/synpress/blob/master/support/index.d.ts#L58-L73

Please upgrade your synpress to latest beta version as it was introduced today, together with `cy.createMetamaskAccount()`:
`@synthetixio/synpress@0.9.25-beta.15`

Give it a go and let me know if it works and suits your needs, thanks!

Cheers,
Jakub.
