### ISSUE TITLE
getting  zsh: number expected while running setupMetamask

### ISSUE THREAD

**Issue by divyag-RC** [Synthetixio/synpress#273]
➜  synpress git:(master) ✗ synpress run setupMetamask('secret phase', 'localhost', 'password')   
zsh: number expected

**Comment by drptbl** [comment]
@divyag-RC I can't understand what the issue is, sorry. You have to provide more details.

Also, this is not how you run synpress. Please refer to the README for more details:
https://github.com/Synthetixio/synpress#readme

**Comment by divyag-RC** [comment]
Please refer the screenshot , I am getting this error , what am i doing wrong
<img width="693" alt="Screen Shot 2021-11-09 at 2 12 02 PM" src="https://user-images.githubusercontent.com/85945451/140905418-344bd4e3-00aa-4470-8895-f6bd9cc81329.png">
 ?

**Comment by drptbl** [comment]
@divyag-RC Error is self-explanatory. You're missing `SECRET_WORDS` or `PRIVATE_KEY` variable.

Again, please follow the readme as it's explained there:
https://github.com/Synthetixio/synpress#-important
<img width="840" alt="Screenshot 2021-11-09 at 12 10 06" src="https://user-images.githubusercontent.com/8177587/140913848-3894e7d1-bc26-431d-8097-061971423a7a.png">
