### ISSUE TITLE
I can't make it work on Gitlab CI

### ISSUE THREAD

**Issue by aguirrel** [Synthetixio/synpress#275]
Hi guys,

Have somebody ever make synpress work with some CI? I'm trying to make it work with Gitlab CI, but it doesn't work.

Thanks a lot!

Best regards,

**Comment by drptbl** [comment]
@aguirrel helpful resources:
- https://github.com/Synthetixio/docker-e2e
- https://github.com/Synthetixio/staking/blob/dev/.github/workflows/audit_build_verify.yml#L108-L187
- https://github.com/Synthetixio/staking/blob/dev/package.json#L17
- https://docs.cypress.io/guides/continuous-integration/introduction
- https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#GitLab-CI
- https://docs.cypress.io/guides/continuous-integration/gitlab-ci#Worker-Jobs

Please provide more details if you need more detailed help and re-open the issue.

Thanks,
Jakub.
