### ISSUE TITLE
How to connect Account2 to my site

### ISSUE THREAD

**Issue by brave-merida** [Synthetixio/synpress#276]
Hi!
I created the Account2 by ```cy.createMetamaskAccount```
And ```cy.switchMetamaskAccount```
But I cannot let the Account2 connect to my website.
How can I resolve this?
Thank you!

**Comment by drptbl** [comment]
Hey @brave-merida.

It sounds like dapp-related thing, not related to synpress itself.

After calling `cy.switchMetamaskAccount`, account is properly switched to another, right?

So now, it depends how your dapp handles this specific case. For example, you could refresh the website in your tests (afte switching your account in metamask) and try to connect wallet again in the dapp. This time it should connect with your other account.

**Comment by drptbl** [comment]
I'm closing this task as it doesn't seem to be related to synpress at all.

Please re-open if you're having any issues with synpress itself.

Thanks,
Jakub.
