### ISSUE TITLE
Apply for Gitcoin grant

### ISSUE THREAD

**Issue by garmeeh** [Synthetixio/synpress#277]
Recently came across this project when trying to see how best to test Dapps. I think it will be invaluable for the community, maybe to help support the development of it you might consider applying for a [Gitcoin grant](https://gitcoin.co/grants/)

**Comment by drptbl** [comment]
> Recently came across this project when trying to see how best to test Dapps. I think it will be invaluable for the community, maybe to help support the development of it you might consider applying for a [Gitcoin grant](https://gitcoin.co/grants/)

https://gitcoin.co/grants/5699/synpress-web3-enabled-e2e-testing-tool
