### ISSUE TITLE
Failing to complete setupMetamask.

### ISSUE THREAD

**Issue by cinjon** [Synthetixio/synpress#278]
I have the following simple test. I've also set it up almost exactly as in the instructions. However, synpress is failing with the following error:

```
cy.task('setupMetamask') failed with the following error:
> waiting for function failed: timeout 30000ms exceeded
Because this error occurred during a before all hook we are skipping the remaining tests in the current suite:
```

Any idea what's going on?

```
describe('mint on the app.', () => {
    before(() => {
      cy.setupMetamask(
        'test test test test test test test test test test test junk',
        'localhost',
        'Tester@1234',
      ).then(setupFinished => {
        expect(setupFinished).to.be.true;
      });
      cy.visit('/')
    })

    it('visits the homepage and logs into web3sso.', () => {      
      cy.visit('/')
      cy.wait(2000)
      cy.get('#web3SSO').contains("Connect").click()
      cy.wait(2000) // wait 2s.
      cy.get('.web3modal-provider-name div').contains("MetaMask").click()
      cy.wait(2000) // wait 2s.
      cy.get('#headlessui-menu-button-3').should('have.text', '0xf39F');
    })
})
```

**Comment by cinjon** [comment]
This is true even if I just copy-paste in https://github.com/Synthetixio/synpress/blob/master/tests/e2e/specs/metamask-spec.js and run it. It always fails to complete the `cy.task('setupMetamask')` function.

**Comment by raparri01** [comment]
I had a similar issue and it took a few rounds of debugging to get this base test case passing. Here's what I noticed / changed:

1. The tsconfig.js in my /tests/e2e was not being picked up by the typescript compiler so I had to make debugging changes to the tsconfig in my project root
2. The application running at localhost didn't accept connections to rpc's with chainId: 42 (kovan) so I made sure it was supported by my rpc connector
3. I was not targeting the right ecmascript target. Changing the target from `es5` to `esnext` got the tests working
4. Needed to set `importHelpers` in my `compilerOptions` to true
5. Needed to install `tslib` and set it's path in the `paths` object of tsconfig

Hope these help you!

**Comment by cinjon** [comment]
Thanks for helping @raparri01 . I switched to using dappeteer (with puppet) and it worked more smoothly.

**Comment by drptbl** [comment]
@cinjon @raparri01 sorry for late response.

You are missing `SKIP_METAMASK_SETUP=true` if you want to use your custom `setupMetamask()` function in tests. In general, you shouldn't be really using it this way if not required.

I recommend sticking with default method which requires you to set environmental variables mentioned in the readme to make it work (like `SECRET_WORDS='test test'` or `PRIVATE_KEY=test`). Then everything is handled automatically for you every test and you don't have to repeat it yourself in your tests.

**Comment by 4ortytwo** [comment]
@drptbl where do you have to set these environment variables?
