### ISSUE TITLE
Metamask Extension Not Opening in Separate Tab

### ISSUE THREAD

**Issue by raparri01** [Synthetixio/synpress#286]
After running `export SECRET_WORDS=some-secret-words; export RPC_URL=https:\/\/kovan.infura.io\/v3\/9aa3d95b3bc440fa88ea12eaa4456161; export CHAIN_ID=42; npx synpress run -b firefox`

The resulting cypress instance not have MetaMask setup open in a separate tab, I am not sure what caused this to happen as it was setting up properly previously.

**Comment by drptbl** [comment]
Hey @raparri01,

Thanks for reporting this issue. Firefox is not yet supported.

To run it on Chrome, you can try:
`SECRET_WORDS='word1, word2, ...' RPC_URL='https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161' CHAIN_ID=42 npx synpress run`

**Comment by raparri01** [comment]
Thanks @drptbl this got it working again
