### ISSUE TITLE
Running `synpress open` causes command to be run in loop

### ISSUE THREAD

**Issue by raparri01** [Synthetixio/synpress#287]
After running `export NETWORK_NAME=rinkeby; export SECRET_WORDS=shuffle\ stay\ hair\ student\ wagon\ senior\ problem\ drama\ parrot\ creek\ enact\ pluck; npx synpress open`

A command is executed in a loop and causes the cypress window to not open: `npm exec synpress run -b firefox`
![image](https://user-images.githubusercontent.com/32496022/143618888-69dbfe82-8d87-4e12-815e-7c7a0184362b.png)

Could possibly be coming from some cached value but not sure what would have caused this behavior in the first place.

**Comment by raparri01** [comment]
^ reinstalling synpress fixed this issue

**Comment by drptbl** [comment]
Firefox is not supported as for now.
