### ISSUE TITLE
Can't connect to dApp after switching account.

### ISSUE THREAD

**Issue by shawnwang0715** [Synthetixio/synpress#294]
When switching accounts in the MetaMask notification window, it would show a prompt to let you connect the next account to your dApp. However synpress switches accounts in a new tab of MetaMask (expanded view). In this case, the prompt won't show, so the new account won't be able to interact with the dApp...

I guess one workaround is that make synpress 'select all' accounts when it makes MetaMask connect to the dApp for the first time.

**Comment by drptbl** [comment]
Hey @shawnwang0715, thanks for feedback.

I will investigate this later today.

**Comment by avp1598** [comment]
Hi @drptbl I have a potential fix for this, which is to accept access to all accounts instead of just 1. However I am not familiar with the process of merging this fix with the library. Should I just raise a PR?

**Comment by drptbl** [comment]
Hey @avp1598, that's great to hear. Yes, please open a new PR. Thanks! 💪

**Comment by DanyalKhawaja** [comment]
I assume you have already resolved it, otherwise   cy.acceptMetamaskAccess(true); will connect all accounts

**Comment by shawnwang0715** [comment]
Yes, I created the PR. Thanks for reminding me to close this issue.
