### ISSUE TITLE
SKIP_RESOURCES_WAIT flag doesn't work

### ISSUE THREAD

**Issue by serzhshakur** [Synthetixio/synpress#295]
`SKIP_RESOURCES_WAIT` is always `null`. This is because `process.env.` is used to retrieve environment variable. 
`Cypress.env()` can be used insted for this work. But due to the fact that [Cypress ignores all environment variables that do not start with `CYPRESS_`](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_) need to set `CYPRESS_SKIP_RESOURCES_WAIT` insted

**Comment by serzhshakur** [comment]
@drptbl can you please review my PR?

**Comment by drptbl** [comment]
@serzhshakur will do it today, thanks a lot and sorry for delay.

**Comment by drptbl** [comment]
Hey @serzhshakur, it has been merged and released as `@synthetixio/synpress@1.1.1`.

Thanks for contribution!

All Best,
Jakub.

**Comment by serzhshakur** [comment]
Hey Jakub,

thanks a lot!
