### ISSUE TITLE
Error launching browser

### ISSUE THREAD

**Issue by XanderJL** [Synthetixio/synpress#315]
Apologies if this is redundant, but I haven't seen any reference to this in the issues. using `@synthetixio/synpress@1.1.1`

```
The launchOptions object returned by your plugin's before:browser:launch handler contained unexpected properties:

width
height
resizable
launchOptions may only contain the properties:

preferences
extensions
args
```

![image](https://user-images.githubusercontent.com/25848639/150833400-7e2a6f65-8661-402a-84b9-ad0defc62541.png)

I'm passing in my env vars with `dotenv-cli` and the test I'm attempting to run is just attempting to visit the landing page of a project:

```js
describe('Metamask', () => {
  before(() => {
    cy.visit('/')
  })
})
```

**Comment by drptbl** [comment]
Hey @XanderJL, thanks for reporting.

I couldn't reproduce the issue, so it seems like setup/user error.

Could you please let me know which command do you use to run your tests?

Also, is your setup available on open web? I could take a quick look and see what's going on.

All Best,
Jakub.

**Comment by XanderJL** [comment]
It's most certainly a user error 😅 

Unfortunately it's a closed repo, but I hope this info suffices!

using `node v16.13.1`
It's a next 12 project using a `./src` dir, so I'm preloading my env vars from `.env.local` with `dotenv-cli`.

Cypress loads up just fine, but when I attempt to run the metamask test, I'm met with the error re: window width x height. I thought this may be a wsl2-related bug, but found the same behavior on an m1 mac.

script from my `package.json`:

```json
"syn:open": "dotenv -e .env.local synpress open"
```

structure from root of project:

```bash
./tests
└── e2e
    ├── config.json
    ├── index.d.ts
    ├── specs
    │   └── metamask.ts
    └── tsconfig.json
```

files in `e2e`:

config.json
```json
{
  "baseUrl": "http://localhost:3000",
  "userAgent": "synpress",
  "retries": { "runMode": 0, "openMode": 0 },
  "integrationFolder": "tests/e2e/specs",
  "screenshotsFolder": "tests/e2e/screenshots",
  "videosFolder": "tests/e2e/videos",
  "chromeWebSecurity": true,
  "viewportWidth": 1366,
  "viewportHeight": 768,
  "component": {
    "componentFolder": ".",
    "testFiles": "**/*spec.{js,jsx,ts,tsx}"
  },
  "env": {
    "coverage": false
  },
  "defaultCommandTimeout": 30000,
  "pageLoadTimeout": 30000,
  "requestTimeout": 30000
}
```

```js
// eslintrc.js
const path = require('path')
const synpressPath = path.join(
  process.cwd(),
  '/node_modules/@synthetixio/synpress'
)

module.exports = {
  extends: `${synpressPath}/.eslintrc.js`
}
```

```ts
// info.d.ts is nearly 300 lines long, but is just copy-pasted from here
// more info: https://github.com/Synthetixio/synpress/blob/master/support/index.d.ts
```

tsconfig.json:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "../../node_modules",
    "types": [
      "cypress",
      "@types/puppeteer-core",
      "@synthetixio/synpress/support",
      "cypress-wait-until",
      "@testing-library/cypress"
    ],
    "outDir": "./output"
  },
  "include": ["**/*.*"]
}
```

```ts
// e2e/specs/metamask.ts
describe('Metamask', () => {
  before(() => {
    cy.visit('/')
  })
})
```

**Comment by ghardin1314** [comment]
Are you sure you have chrome installed? I had this issue also and I think it was because cypress was trying to use electron

https://github.com/Synthetixio/synpress/blob/e47f4cadc05aeb8c580a124805b5e29a0caedd02/plugins/index.js#L21-L26

**Comment by XanderJL** [comment]
Oh my gosh. Switching to chrome fixed it 🤦 

![image](https://user-images.githubusercontent.com/25848639/151039174-aa80c690-f63b-40e0-8ef5-70fd4962f5e2.png)

Totally was user error. Sorry for the fuss @drptbl and thanks for pointing me in the right direction @ghardin1314 😅

**Comment by drptbl** [comment]
No worries @XanderJL, glad that you've sorted it out.

Thanks for helping out @ghardin1314!

Cheers,
Jakub.
