### ISSUE TITLE
confirmMetamaskSignatureRequest failing => timeout

### ISSUE THREAD

**Issue by kabaneridev** [Synthetixio/synpress#323]
Hi,

There is problem with method 
`cy.confirmMetamaskSignatureRequest();` => it leads to timeout error when trying to sign message.
```
CypressError: `cy.task('confirmMetamaskSignatureRequest')` failed with the following error:

> waiting for function failed: timeout 30000ms exceeded

https://on.cypress.io/api/task
```
<img width="349" alt="Screenshot 2022-02-07 at 13 04 13" src="https://user-images.githubusercontent.com/48051231/152784817-3968a719-76f6-40e6-a884-46bd98750352.png">

![Screenshot 2022-02-07 at 13 05 36](https://user-images.githubusercontent.com/48051231/152784974-172750f5-fb46-4634-a766-c25e8a27f02e.png)

what may be the reason?

**Comment by jakzaizzat** [comment]
Hey @kabaneridev I faced the same issue. It seems inconsistent. 

How do you fix it?
