### ISSUE TITLE
Broken Selector for confirmMetamaskSignatureRequest();

### ISSUE THREAD

**Issue by saur-bh** [Synthetixio/synpress#325]
### Discussed in https://github.com/Synthetixio/synpress/discussions/324

<div type='discussions-op-text'>

<sup>Originally posted by **saur-bh** February  7, 2022</sup>
After investigation found that selector needs to be corrected in 
@synthetixio/synpress/pages/metamask/notification-page.js as 
{code}
const confirmSignatureRequestButton = `${notificationPage} .signature-request-footer :last-child`;
const rejectSignatureRequestButton = `${notificationPage} .signature-request-footer :first-child`;
{code}

which is 
{code}
const confirmSignatureRequestButton = `${notificationPage} .request-signature__footer__sign-button`;
const rejectSignatureRequestButton = `${notificationPage} .request-signature__footer__cancel-button`;
{code}</div>

**Comment by ghardin1314** [comment]
I am also having an issue with this method using MM v9.7.1. Not sure if its related but I think it has to do with `eth_sign` vs `signTypedData_v4`. The former works just fine to sign arbitrary strings but using the later hangs for both `confirmMetamaskSignatureRequest` and `rejectMetamaskSignatureRequest`

Using ethers to interact with MM if that makes any difference

**Comment by pcardosolei** [comment]
Hi @saur-bh 

Where does it stop when running the tests?

In my cases it does not go through the account selection in the Metamask wallet. 
It is very strange because if i use run the command cypress open it works (it selects the account 1). 

When i run "cypress run"
I'm using the Synpress as a plugin within cypress because i don't want to have setup Metamask at all the files.

**Comment by pcardosolei** [comment]
A bit more context.

![Screenshot 2022-04-22 at 14 03 16](https://user-images.githubusercontent.com/10116142/164719707-a3628720-9e7c-4889-b141-e249e72360a5.png)
![Screenshot 2022-04-22 at 14 03 21](https://user-images.githubusercontent.com/10116142/164719710-28b47ce1-3472-4228-9bbf-792e80b3b544.png)

**Comment by pcardosolei** [comment]
did some debugging.

https://github.com/Synthetixio/synpress/issues/398

not sure if related.

**Comment by drptbl** [comment]
`@synthetixio/synpress@3.0.0` has been released which includes metamask@10+ update solving this issue. Please reopen if not, thanks!

**Comment by 0xmad** [comment]
Seems metamask changed `data-testid` for signing.
For 10.28.1 version it's `page-container-footer-next` for sign button and `page-container-footer-cancel` for reject button.

![image](https://user-images.githubusercontent.com/14254374/232618020-8b93b09d-a397-45aa-866e-85e062eaa069.png)
