### ISSUE TITLE
How can I add/import a token

### ISSUE THREAD

**Issue by blackpintz** [Synthetixio/synpress#331]
Hi, is there a function that I can use to add/import a token?

**Comment by drptbl** [comment]
Hey @blackpintz. Sadly there is no such function yet, but I will try to implement it until end of this week. Expect it to be included in next synpress release, which is expected until Monday.

Cheers,
Jakub.

**Comment by blackpintz** [comment]
@drptbl Okay, thank you. Another issue I am having is trying to call `confirmMetamaskTransaction()`. I keep getting this error:
```
     CypressError: `cy.task('confirmMetamaskTransaction')` failed with the following error:

> waiting for function failed: timeout 30000ms exceeded
```
Not sure if it is me calling it wrongly.
You can find my code for this here: https://github.com/blackpintz/FE-Challenge/tree/e2e-tests
And I am using `synpress run`. Please advise.

**Comment by blackpintz** [comment]
> @drptbl Okay, thank you. Another issue I am having is trying to call `confirmMetamaskTransaction()`. I keep getting this error:
> 
> ```
>      CypressError: `cy.task('confirmMetamaskTransaction')` failed with the following error:
> 
> > waiting for function failed: timeout 30000ms exceeded
> ```
> 
> Not sure if it is me calling it wrongly. You can find my code for this here: https://github.com/blackpintz/FE-Challenge/tree/e2e-tests And I am using `synpress run`. Please advise.

It worked when I used `cy.confirmMetamaskPermissionToSpend()` instead.

**Comment by drptbl** [comment]
Hey @blackpintz, this has been added in latest synpress version which is `@synthetixio/synpress@3.0.3`.

- `cy.confirmMetamaskAddToken()` (to confirm adding a new custom token)
- `cy.importMetamaskToken('0x509ee0d083ddf8ac028f2a56731412edd63223b9')`
or
- `cy.importMetamaskToken({ address: '0x509ee0d083ddf8ac028f2a56731412edd63223b9', symbol: 'USDT'})` (to set custom symbol)

Thanks,
Jakub.
