### ISSUE TITLE
confirm / provide Request encryption public key

### ISSUE THREAD

**Issue by maxhoheiser** [Synthetixio/synpress#340]
Hi, I want to confirm the request to provide a encryption public key with synpress, but I could not find it as a custom command. Is there a way to confirm arbitrary requests to metamask independent of the type via puppeteer?

**Comment by maxhoheiser** [comment]
I tried to implement a new custom command for it, but I am stuck getting puppeteer to find the right buttons.

I tried adding following element to `notivication-page.js`

```
const confirmEncryptionPublicKeyButton = `${notificationPage} .request-encryption-public-key__footer__sign-button`;
const rejectEncryptionPublicKeyButton = `${notificationPage} .request-encryption-public-key__footer__cancel-button`;
module.exports.encryptionPublicKeyPageElements = {
  confirmEncryptionPublicKeyButton,
  rejectEncryptionPublicKeyButton,
};
```

based on the class of both buttons
![image](https://user-images.githubusercontent.com/15856892/155175655-a9f64842-9958-4900-9cef-26d39c3f5109.png)

I also created the new command both in `metamask.js` and in added it to cypress as a custom command in `index.js`
```
  confirmDecryptionRequest: async () => {
    const notificationPage = await puppeteer.switchToMetamaskNotification();
    await puppeteer.waitAndClick(
      decryptPageElements.confirmEncryptionPublicKeyButton,
      notificationPage,
    );
    await puppeteer.metamaskWindow().waitForTimeout(3000);
    return true;
  },
```

```
    confirmMetamaskDecryptionRequest: async () => {
      const confirmed = await metamask.confirmDecryptionRequest();
      return confirmed;
    },
```

**Comment by drptbl** [comment]
@maxhoheiser included in this release: `@synthetixio/synpress@1.2.0`.

Thanks for contribution!
