### ISSUE TITLE
default gas on kovan breaks e2e 

### ISSUE THREAD

**Issue by moshmage** [Synthetixio/synpress#343]
https://github.com/Synthetixio/synpress/blob/90cafd68218434081a1c7a22c9577084bfba9fc7/commands/metamask.js#L447

Why is this default to `1` when we provide a `gasConfig`?

**Comment by drptbl** [comment]
Hey @moshmage, thanks for report. I will fix it today. Sorry for the delay.

**Comment by drptbl** [comment]
Hey @moshmage, sorry for such a big delay, again.

This has been fixed and released as `@synthetixio/synpress@1.2.1-beta.0`. Thanks for reporting!

**Comment by moshmage** [comment]
> Hey @moshmage, sorry for such a big delay, again.
> 
> This has been fixed and released as `@synthetixio/synpress@1.2.1-beta.0`. Thanks for reporting!

np mate, we all have lives :)

Thanks for pinging!
