### ISSUE TITLE
npm install --save-dev @synthetixio/synpress fails

### ISSUE THREAD

**Issue by L-TheG** [Synthetixio/synpress#379]
Hi I am having issues installing using npm.

`npm install --save-dev @synthetixio/synpress fails` 
fails with:
`npm ERR! code ENOENT`
`npm ERR! syscall spawn git`
`npm ERR! path git`
`npm ERR! errno -4058`
`npm ERR! enoent An unknown git error occurred`
`npm ERR! enoent This is related to npm not being able to find a file.`
`npm ERR! enoent`

I tried using the --legacy-peer-deps flag aswell

I am using 
Node v16.13.0
npm v8.3.0

Clearing npm cache and deleting node_modules did not solve the issue.

This is the relevant part of the npm debug log:
4709 verbose stack Error: An unknown git error occurred
4709 verbose stack     at makeError (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
4709 verbose stack     at C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:36:26
4709 verbose stack     at runMicrotasks (<anonymous>)
4709 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
4710 verbose cwd C:\Users\<user>\Path\To\Project\root
4711 verbose Windows_NT 10.0.19043
4712 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save-dev" "@synthetixio/synpress"
4713 verbose node v16.13.0
4714 verbose npm  v8.3.0

Is this an issue with npm, git, node or with your package?

Thanks!

**Comment by L-TheG** [comment]
I tried again with the newest npm version (v8.6) and a completely empty node project, leading to the same result.

**Comment by L-TheG** [comment]
I managed to fix this by putting cypress and synpress into the package.json file and then installing them both at the same time using "npm i"

No idea why this worked but "npm i @synthetixio/synpress cypress" did not work.

**Comment by drptbl** [comment]
Hey @L-TheG, thanks for letting me know. I will make sure to verify what's going with Windows and get back to you.

Cheers!

**Comment by L-TheG** [comment]
Ok after some more experimenting, it turns out it does actually work with only adding synpress (explicitly adding cypress not necessary) to the package.json. So it seems to only be the "npm i synpress" command that seems to be the issue
