### ISSUE TITLE
Cypress freezing after triggering transaction

### ISSUE THREAD

**Issue by L-TheG** [Synthetixio/synpress#405]
Cheers!

I am trying to test a transaction.
After the button to trigger the transaction is pressed, no MetaMask window to confirm the transaction appears and the Cypress UI becomes unresponsive. The confirmMetamaskTransaction() function obviously doesn't work when no transaction-confirmation window is showing.
No UI-Element in the Cypress test runner is clickable.
The Chrome UI (switching tabs etc.) still works. 
There are not transactions listed when inspecting the MetaMask tab in the Chrome window.
Testing the failing transaction manually works as expected.

A button with exactly the same functionality (calling the same function in the same context) exists on another site of the website I am testing. Triggering the same transaction using that quasi-identical button through Synpresss does work.

Synpress gets invoked using the 'run' option and I have isolated the test to make sure there is no interference with another test.

Any ideas what could be causing this?
Thanks!

**Comment by pcardosolei** [comment]
Can you provide like a video so I can try to help?

**Comment by L-TheG** [comment]
I am sorry but I found a workaround and can't reproduce it anymore. It seemed like it had something to do with the browser cache and local storage being deleted between tests. I can't figure out how that would make Cypress crash though.

I guess this Issue is fine to be closed right?
