### ISSUE TITLE
'Localhost' not always the best option

### ISSUE THREAD

**Issue by josepmc** [Synthetixio/synpress#421]
Depending on the system configuration, `await fetch('http://localhost:9222/json/version');` may not work (specifically on macOS).

A working alternative is using the address `0.0.0.0`. If you're happy with this I can whip a PR and get it over.

**Comment by drptbl** [comment]
@josepmc thanks for reporting, fixed with 127.0.0.1.
https://github.com/Synthetixio/synpress/commit/63c3b682641c5daf53e5230b37d14d5b63e02ea3
