### ISSUE TITLE
Plugin crashes when connecting to Metamask

### ISSUE THREAD

**Issue by nl0243** [Synthetixio/synpress#447]
I have an issue when running synpress it opens the browser and page successfully, but the metamask page stays empty and then the app crashes. The terminal error:

We stopped running your tests because a plugin crashed.
Your pluginsFile threw an error from: path_to_project\node_modules\@synthetixio\synpress\plugins\index.js

Im using custom config:
```
{
  "baseUrl": "page_link",
  "userAgent": "synpress",
  "retries": { "runMode": 0, "openMode": 0 },
  "integrationFolder": "cypress/integration/specs",
  "chromeWebSecurity": true,
  "component": {
    "componentFolder": ".",
    "testFiles": "**/*spec.{js,jsx,ts,tsx}"
  },
  "env": {
    "coverage": false
  }
}
```

Im running the script using:
- Node v16.16.0
- Cypress 9.5.3
- Chrome 103

**Comment by drptbl** [comment]
Hey, this is old and probably not relevant to latest synpress version. If this issue still persists, please re-open. Thanks!
