### ISSUE TITLE
confirmMetamaskTransaction failed with timeout error -

### ISSUE THREAD

**Issue by Vishwas-02** [Synthetixio/synpress#448]
Hey , I am working on automation testing of Dapp. Till now everything went smoothly , like Dapp connected with wallet and before that MM was smoothly initialised . But afterwards when I confirmed transaction , test failed with following Error - 

![image](https://user-images.githubusercontent.com/101315014/178266031-ae81e32f-da0a-449a-88a2-429ce4601666.png)

I am using synpress version 1.2.0

**Comment by drptbl** [comment]
Hey, this is old and probably not relevant to latest synpress version. If this issue still persists, please re-open. Thanks!
