### ISSUE TITLE
Getting CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

### ISSUE THREAD

**Issue by DevKhaira** [Synthetixio/synpress#449]
│ Cypress:        9.5.3                                                                          │
  │ Browser:        Chrome 103                                                                     │
  │ Node Version:   v17.3.1 (/usr/local/bin/node)                                                  │
  │ Specs:          1 found (login.specs.ts)    |

This is happening in the   1) "before all" hook for "Connects with Metamask"

Is there any work around to this?

**Comment by DevKhaira** [comment]
Just to add more detail it opens the metamask plugin and the get started button shows

**Comment by ishaba** [comment]
same for me stays on metamask welcome page

**Comment by mati-wegotcha** [comment]
Can you write your package.json dependencies?

If you are using `jest@27` you will experience this error. Try to downgrade to `jest@26`

**Comment by Afitzy98** [comment]
> 

I can confirm that jest@26 does not resolve this issue for me on M1 Mac. It seems to work fine on Linux & Windows

**Comment by Afitzy98** [comment]
It works fine on jest@27 for Linux & Windows that is

**Comment by marko911** [comment]
Go to your macos preferences and make sure you have the applications that invoke cypress whitelisted in the automation permissions like so:
<img width="648" alt="Screen Shot 2022-08-31 at 11 55 16 AM" src="https://user-images.githubusercontent.com/15694731/187651926-4b396d76-b14d-43b6-8496-67b97c6c278b.png">

**Comment by drptbl** [comment]
Hey, this is old and probably not relevant to latest synpress version. If this issue still persists, please re-open. Thanks!

**Comment by YakovL** [comment]
@drptbl Should we reopen this one or should I open a new issue? (looks like I can't reopen it) I'm facing this from time to time, without changing anything in config or tests (but can't really say what causes it). I'm using Synpress 3.7.1 and Cypress 12.13.0

![image](https://github.com/Synthetixio/synpress/assets/1131924/3f953804-1643-4c4f-adea-300b10d4fff2)
