### ISSUE TITLE
Error:     CypressError: `cy.task('setupMetamask')` failed with the following error:  > Cannot read properties of undefined (reading 'waitForTimeout')

### ISSUE THREAD

**Issue by NatalieXSelina** [Synthetixio/synpress#463]
![image](https://user-images.githubusercontent.com/108204536/183982597-b3aebf26-3aa5-4313-96c0-8d041ca07b8b.png)

I clone this repository: https://github.com/yvesbou/synpress_metamask_login

After that, I edit file plugins/index.js to register cy.task()
``` js
"use strict";

var _plugins = _interopRequireDefault(require("@synthetixio/synpress/plugins"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

module.exports = (on, config) => {
  (0, _plugins.default)(on, config);
  on('before:browser:launch', (browser, launchOptions) => {
    if ((browser.name === 'chrome' || browser.name === 'edge') && browser.isHeadless) {
        launchOptions.args.push('--disable-gpu');
        return launchOptions
    }
});
};
```

————————

Also, after few times retry, I saw another Issue ( The same as following):
https://github.com/yvesbou/synpress_metamask_login/issues/1

————————

And another less important issue:
the .env file does not work. I have tried to use "env-cmd" and "dotenv" to mange .env, but failed

————————

Windows 10
node v16.14.0

————————

Looking forward to your reply! Thank you.

**Comment by NatalieXSelina** [comment]
I think I found a temporary solution.
Add the path of MetaMask to cypress\plugins\index.js, to let MetaMask setup page to appear.

`      
launchOptions.extensions.push(
        'path/to/extension/MetaMask',
      );
`
I hope this is useful to others as well.

But I think the steps to open the extensions page should already be in the code.

**Comment by drptbl** [comment]
Hey @NatalieXSelina,

Can you retry with `@synthetixio/synpress@2.0.1`?

Thanks for reporting :pray:.

**Comment by drptbl** [comment]
Let me know if this issue still persists. Thanks!

**Comment by quiet-node** [comment]
@drptbl Hello this seems to happen again

I use it in a support.js file
import '@synthetixio/synpress/support/index';

And I got this same error 
![image](https://github.com/user-attachments/assets/e224ec4b-e37a-44f5-957f-6b3ceab81f21)


Currently using latest synpress "@synthetixio/synpress": "^3.7.3",
