### ISSUE TITLE
2.0.1 release interferes with CRACO?

### ISSUE THREAD

**Issue by alexo382** [Synthetixio/synpress#485]
I just upgraded to 2.0.1 and it seems like our react app no longer starts (see error below). We use CRACO (Create React App Configuration Override) to override the default CRA webpack config, and it seems like its dependencies vanish when using Synpress 2.0.1.

```
$ craco start
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'browserify-zlib'
```

```
$ craco start
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'html-webpack-plugin'
```

Did anyone else encounter this issue with the latest release?

Thanks!

**Comment by drptbl** [comment]
Thanks for reporting @alexo382.

Could you link me a repository where I could reproduce this issue, please?

Thanks,
Jakub.

**Comment by alexo382** [comment]
> Thanks for reporting @alexo382.
> 
> Could you link me a repository where I can reproduce this issue, please? 🙏
> 
> Thanks, Jakub.

The repo for our project is private but I'll try reproducing it in a barebones repo and I'll link it here tomorrow. Thanks a lot!

**Comment by drptbl** [comment]
@alexo382 Could you try again with `@synthetixio/synpress@2.0.2-beta.0`?

Thanks,
Jakub.

**Comment by alexo382** [comment]
@drptbl I gave it a try and the result is the same :(

Here's a minimal example that reproduces my issue: https://github.com/alexo382/synpress-test

Let me know if you get the same error when starting the project.

Thanks again!

**Comment by drptbl** [comment]
@alexo382 I have done a review on this.

Can you remove synpress dependency and try to run `craco start` or build?
It doesn't work for me, so it's seems not related to synpress, but craco.

Thanks,
Jakub.

**Comment by alexo382** [comment]
> @alexo382 I have done a review on this.
> 
> Can you remove synpress dependency and try to run `craco start` or build? It doesn't work for me, so it's seems not related to synpress, but craco.
> 
> Thanks, Jakub.

Hey @drptbl, I managed to get around the CRACO issue. Unfortunately now I'm having trouble loading a custom config file, I raised another issue here https://github.com/Synthetixio/synpress/issues/492 😅
