### ISSUE TITLE
Cannot add networks on current version of metamask

### ISSUE THREAD

**Issue by roninjin10** [Synthetixio/synpress#509]
Because of a metamask bug it is not possible to add a local network to metamask.    I tried METAMASK_VERSION=10.15.0 but synpress does not work on this version.

https://github.com/MetaMask/metamask-extension/issues/14416

**Comment by drptbl** [comment]
MetaMask update is planned for this week. Should be done by EOW. Thanks for report! 🙏

**Comment by roninjin10** [comment]
Closing as dupe since it's only related to metamask,
