### ISSUE TITLE
cy.setupMetamask() is not setting up a new wallet

### ISSUE THREAD

**Issue by AndrianoTasev** [Synthetixio/synpress#527]
before(() => {
    cy.setupMetamask({
      secretWordsOrPrivateKey:
        "first, test, test, test, test, test, test, test, test, test, test, junk",
      network: "eth",
      password: "Somepassword00*",
    });

Is there a way to create a new metamask wallet every time when i run test? Right now its importing already existing wallet

**Comment by drptbl** [comment]
@AndrianoTasev Hey, you have to handle this by yourself. You can use combination of `createMetamaskAccount` with `switchMetamaskAccount`.

**Comment by stavares843** [comment]
i tried that and doesn't work

if i use`createMetamaskAccount` 5x times and then i repeat that again that command 5x it will generate the same 5 accounts

a specific seed will always generate the exact same group of keys

**Comment by stavares843** [comment]
you can use

````
console.log(require('crypto').randomBytes(32).toString('hex'))
cy.importMetamaskAccount(require('crypto').randomBytes(32).toString('hex'));
``` 

as suggested by the synpress team at their Discord server 🔨
