### ISSUE TITLE
 cy.addMetamaskNetwork() is not adding the network to the wallet account and its throwing and error for network not visible

### ISSUE THREAD

**Issue by AndrianoTasev** [Synthetixio/synpress#529]
Tried to add new network to the test: 
 cy.addMetamaskNetwork({
      networkName: "Ethereum Dev",
      rpcUrl: "URL",
      chainId: "1",
      symbol: "ETH",
      blockExplorer: "BLOCK",
    });
   
   But i am getting this error:
     **From Node.js Internals:
    TimeoutError: locator.waitFor: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".typography >> :scope:has-text("ethereum dev")" to be visible
    ============================================================
    locator.waitFor: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".typography >> :scope:has-text("ethereum dev")" to be visible
    ============================================================**
SYNPRESS VERSION - 2.3.0

**Comment by drptbl** [comment]
Hey @AndrianoTasev, can you try to change your `networkName` to lowercase which is `ethereum dev` and let me know if that helps?

Thanks,
Jakub.

**Comment by drptbl** [comment]
@AndrianoTasev Thanks for letting me know. I will fix this issue asap!

**Comment by drptbl** [comment]
Hey @AndrianoTasev, sorry for bothering you again.

I have checked this out and it seems that we have e2e test for this specific case:
https://github.com/Synthetixio/synpress/blob/dev/tests/e2e/specs/metamask-spec.js#L43-L56
As you can see - I'm using `Polygon Network` (which is not lowercase) - and it works just fine.
Synpress adds it in lowercase by default and then switches to it without issues.

I'm trying to figure out why it didn't work for you. I have also tried to use your example from this issue and it also worked without issues on my localhost.

Is there any chance you could provide more details about this? Could you try this example with latest synpress version? Full example of your e2e test would be also very helpful.

Thanks,
Jakub.

**Comment by AndrianoTasev** [comment]
Hey  Jakub@drptbl, no worries its a pleasure for me. The version i am using is 2.3.0. This is the code example:

 **before(()=> {
 cy.addMetamaskNetwork({
      networkName: "Ethereum Dev",
      rpcUrl: "URL example",
      chainId: "1",
      symbol: "ETH",
      blockExplorer: "Explorer",
    });
 });**

**Comment by drptbl** [comment]
This should be fixed in latest synpress release.
