### ISSUE TITLE
cy.disconnectMetamaskWalletFromAllDapps() is not proceeding forward with execution if Metamask is not connected already

### ISSUE THREAD

**Issue by dewanshparashar** [Synthetixio/synpress#534]
While calling c`y.disconnectMetamaskWalletFromAllDapps()`,
Disconnect-metamask-wallet hangs the cypress execution flow indefinitely if already not connected to metamask. 
Ideally, it should resolve the promise successfully if it doesn't detect the metamask connection already.

If this is done deliberately by design, it should be communicated in the documentation. If that's the case, I can close this issue and raise a PR for the same.

**Comment by drptbl** [comment]
@dewanshparashar thanks for reporting. I think that ` cy.disconnectMetamaskWalletFromAllDapps()` should be improved. I will take care of this today ;).

**Comment by drptbl** [comment]
@dewanshparashar This has been fixed in `@synthetixio/synpress@2.4.0-beta.0`. Could you try it and let me know if that fixes your issue, please? Thanks 🙏.
