### ISSUE TITLE
SetupMetamask is not working when executing it in FireFox

### ISSUE THREAD

**Issue by AndrianoTasev** [Synthetixio/synpress#543]
<img width="1249" alt="Screenshot 2022-10-11 at 10 50 17" src="https://user-images.githubusercontent.com/11423415/195042219-ac09d881-a344-4ba9-84f1-84486b77a9c3.png">

Cypress version - 2.3.0
script for test execution - env-cmd -f .env npx synpress run -b firefox -r mochawesome --configFile='synpress.config.js'

Chrome is working,
Edge is working
FireFox fail

**Comment by drptbl** [comment]
@AndrianoTasev Chrome is the only supported browser for now.

**Comment by AndrianoTasev** [comment]
@drptbl Got it, thank you!
