### ISSUE TITLE
addMetamaskNetwork() is invoked twice

### ISSUE THREAD

**Issue by mflorlorenzo** [Synthetixio/synpress#557]
Having this function in my "before" inside the "describe", it's adding the network in the global "before", and then try to add this again when my "before" runs, dunno why :/

**Comment by drptbl** [comment]
@mflorlorenzo After passing environmental variables related to custom network while starting synpress => you don't have to invoke `addMetamaskNetwork()` again inside your tests. I think this is the issue.
