### ISSUE TITLE
Metamask notification does not appear

### ISSUE THREAD

**Issue by FrancescoPG** [Synthetixio/synpress#592]
I'm currently writing E2E tests for our application and strange behavior occurs. Running the application manually everything works correctly, but if you run the same steps via synpress an error occurs. Specifically: clicking a button triggers an invocation of a contract via ethers.js and the metamask notification (the window where you accept the transaction) does not appear but is intercepted as shown in image below.

![image](https://user-images.githubusercontent.com/119883592/205700073-d806498f-58ef-456f-a933-2a8448cc5f5d.png)

If the notification is not shown, the test fails.

## Contract invocation
The contract is invoked via ether.js as follows:
```typescipt
const contract: Contract = new ethers.Contract(contractAddress, abi, signer);
contract.createToken(metadata, selectedAddresses, { from: address, gasLimit: process.env.GAS_LIMIT })
```

## Tests execution
Tests are executed like below:
```typescipt
cy.findByTestId("trigger_transaction_button").click();
cy.confirmMetamaskTransaction().then((txData)=>{
    expect(txData).not.null;
    expect(txData.confirmed).to.be.true;
})
```

## Result
Test fails as follow:
![image](https://user-images.githubusercontent.com/119883592/205701467-6e65bb2d-ceff-4885-8bb8-e4d443a1e81b.png)

## Enviroment
**OS**: windows 10
**Node**: 16.14.0
**Synpress**: 3.0.5
**ethers**: 5.7.2
**next**: 13.0.2

Any suggestions?

**Comment by drptbl** [comment]
Hey @FrancescoPG, I can see that you're using Windows. Have you tried to run the same setup on Linux or macOS?

**Comment by drptbl** [comment]
also, do you have any website where I can reproduce this issue?

Thanks,
Jakub.

**Comment by FrancescoPG** [comment]
Hi @drptbl thanks for your suggestion. I tested the same setup on linux, Ubuntu 18 and there is exactly the same problem. Further detail, even if I don't think it's influential, in the linux environment the version of node is 16.
Unfortunately I don't have any websites to provide to replicate the problem, they are local developments.

**Comment by drptbl** [comment]
Hey @FrancescoPG,

Sorry for inconvenience.

Can you try again with `@synthetixio/synpress@3.1.0` and report back?

This issue should be fixed now.

Also, if you're using `docker-e2e`, I suggest to update to one of these:
```
- synthetixio/docker-e2e:14.21-debian
- synthetixio/docker-e2e:16.19-debian
- synthetixio/docker-e2e:18.13-debian
```
or..
```
- synthetixio/docker-e2e:14.21-ubuntu
- synthetixio/docker-e2e:16.19-ubuntu
- synthetixio/docker-e2e:18.13-ubuntu
```

Thanks,
Jakub.

**Comment by drptbl** [comment]
Hey, this should not be a case anymore.

Please use provided examples inside [CI tips & tricks](https://github.com/Synthetixio/synpress#ci-tips--tricks) section.

Also, make sure you're on latest `@synthetixio/synpress@3.2.0`.

In details your setup is probably missing `xvfb` and window manager dependencies.

If you're still going to encounter this issue, please re-open.

Thanks,
Jakub.
