### ISSUE TITLE
RPC Error: Pending wallet request will fail to open notification

### ISSUE THREAD

**Issue by Jofairden** [Synthetixio/synpress#601]
# The problem
There's an issue within Synpress that is hard to deal with and that is the error (see title) that originates from within Metamask itself when there's already a connection pending.

# Reproduction
This can easily be reproduced by programming a simple dApp with a connect wallet.
First, use cypress to click connect wallet and then use `cy.acceptMetamaskAccess()` to approve the connection.
When done with the test, use `cy.disconnectMetamaskWalletFromDapp()`.
When returning, click connection again and try to accept the access once more. 
This might fail when metamask is remembering an underlying pending approval, rather than opening a new window. 

Example (pseudocode)
```javascript
describe('Simple connection test', () => {
  context("Test connection on first page" , testConnection(..page))
  context("Test connection on second page" , testConnection(..page))
  
  afterEach(() => {
    cy.disconnectMetamaskWalletFromDapp()
  }
  
  function testConnection(page) {
    return () => {
      before(() => {
        page.visit()
      }
      
      it("Should be able to connect", () => {
        page.connectWalletButton.click()
        cy.log("Connected: " + cy.acceptMetamaskAccess())
      }
    }
  }
}
```

# Issue Diagnosis
## Diagnosis tree
1. plugins\index.js - > acceptMetamaskAccess -> metamask.acceptAccess
2. commands\metamask.js ->playwright.switchToMetamaskNotification
3. commands\playwright.js

## Window switching
`switchToMetamaskNotification` within `playwright.js` uses an arbitrary '50' retry mode with a small delay within each try (realized as a recursive function call) that continuously tries to grab a window which url includes 'notification'. This works if metamask opens the transaction as a new window, which it doesn't do _if the approval is pending in the background_. When it is metamask will throw the error in the title. 

## Going to the appropriate window
The notification itself can be found within extension: .. / notification.html

### Chromium
Within chromium it is easy to find this window, because the extension ID can be found easily using the chrome store:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn 
-> **nkbihfbeogaeaoehlefnkodbefgpgknn**

Those files can then be accessed using base url `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/`
So the notification can be found in `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/notification.html`

### Gecko
Within firefox is a little harder, because the addons use a randomized ID within the runtime.
We can navigate to `about:debugging#/runtime/this-firefox`
And playwright can find the id by looking for "Metamask" and the internal UUID field.
The plugin can then be accessed at: (example)
`moz-extension://17e0af3d-c1cc-442c-b60f-7ea82b39c627/`
So the notification can be found in `moz-extension://17e0af3d-c1cc-442c-b60f-7ea82b39c627/notification.html`

### Generalized approach
However, a more fool proof way would be to simply open popup.html as that would automatically redirect itself to the connection logic: (the url should use the #connect anchor)
`chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html`
`moz-extension://17e0af3d-c1cc-442c-b60f-7ea82b39c627/popup.html`

# Proposed Change
I propose that the logic on how metamask windows get used within synpress are changed to directly call the plugin windows. This is already done upon start by using playwright to open the metamask plugin window. Using the popup page for direct access within a new tab, rather than scouring for a popup which cannot be triggered. This means some of the logic within the playwright.js will have to change, such as the window assignment. In my mind, popup.html could always be used considering that is what the plugin opens when the metamask icon is manually clicked.

## Possible implementation
The following is a draft/generic outline:

* Manager class that has one implementation based on the browser engine. Chrome or Gecko (are there other browsers supported with other Add-Ons?). Later on it's possible to keep it even broader and call it WalletManager for potential support of other wallets in the future
* The manager class gets initialized when cypress runs
* The manager can also keep track of the engine, which gets set in init() within playwright.js, but I'm unsure about the specifics
* Switching to Metamask should be as easy as navigating in a new tab to /popup.html, and/or keeping track of the existing tab and use that. 
* Verifying the state should be possible by asserting the url within the /popup.html page, as metamask seems to create anchors when the state has changed. For example with a confirmation: /popup.html#confirmation 
* Using just the popup.html in a tab should be enough, as that page is dynamically changing to what is happening within metamask

Classes outline:

**Manager Interface**:
- getAddonId()
- ensureMetamaskIsOpen()
- switchToMetamask()
- assertState(state)

These methods should be enough.

`getAddonId()` will be returning the ID or UUID for the addon. For chrome this will be set to the plugin ID. Within firefox we need to register the UUID that was assigned in the runtime as stated above. It looks like that UUID varies for each runtime, so it would be wise to grab the UUID every session if it doesn't hinder performance.

`ensureMetamaskIsOpen()` will be used to ensure that we have the metamask window opened and tracked. If it somehow got closed by any means, this method should ensure that the window is opened again.

`switchToMetamask()` would be the logic to switch to the tab and navigating to the popup page using the AddonId method, the tab may have to be reloaded to refresh the state

`assertState(state)` would be a check to confirm that the popup window got into the expected state, such as #confirmation (this will be handy in the scenarios where we don't end up in the state we expect and fix bugs)

Within `playwright.js` we can change `switchToMetamaskNotification` to now simply address the manager class, and call `switchToMetamask()`. We should also be able to merge this with `switchToMetamaskWindow`, as we no longer really need the concept of using the notification. Using the full window is more reliable. So in the end we should only have `switchToCypressWindow()` and `switchToMetamaskWindow()`.

I then propose to simplify the logic behind 'activeTabName' and replace it with a boolean `isCypressWindowActive`, which we can keep false while we're in the metamask window. This will get rid of tracking `activeTabName`, `isMetamaskNotificationWindowActive`, and 'isMetamaskWindowActive' can simply return !isCypressWindowActive.

I would also suggest changing `assignWindows()` to ensure more reliability, and use the manager to ensure the tab is open during the assignment. So instead of tracking the page urls, using the manager's `ensureMetamaskIsOpen()` method and then grabbing the return value, which would be the the metamask tab that was ensured to be open.

Overall I think this limits the additions and changes neatly, as the logic within `metamask.js` still simply calls the `playwright.js` implementation, which is altered and simplified.

# Related issues (that should be fixed)

https://github.com/Synthetixio/synpress/issues/592

**Comment by drptbl** [comment]
Hey,
First of all - thank you for your report. It's awesome, clear and ready to be worked on.

I will rewrite the logic for metamask windows when I have some free time (beginning of January). In the meantime maybe someone else will pick this up, but if not - Jan is my deadline.

Thanks,
Jakub.

**Comment by Jofairden** [comment]
@drptbl I added my angle of attack in the original post. That's what I think of it with the (limited) knowledge of Synpress that I have. Obviously you know more ins and outs. Let me know if it sounds good to you.

**Comment by drptbl** [comment]
@Jofairden Love it, makes sense and it will be easy to extend it in future. Great job 💪.

**Comment by francesco-gaglione** [comment]
Any news on this?

**Comment by drptbl** [comment]
Hey @Jofairden @francesco-gaglione @mitsudani,

Sorry for inconvenience.

Can you try again with `@synthetixio/synpress@3.1.0` and report back?

This issue should be fixed now.

Also, if you're using `docker-e2e`, I suggest to update to one of these:
```
- synthetixio/docker-e2e:14.21-debian
- synthetixio/docker-e2e:16.19-debian
- synthetixio/docker-e2e:18.13-debian
```
or..
```
- synthetixio/docker-e2e:14.21-ubuntu
- synthetixio/docker-e2e:16.19-ubuntu
- synthetixio/docker-e2e:18.13-ubuntu
```

Thanks,
Jakub.

**Comment by drptbl** [comment]
Hey, this should not be a case anymore.

Please use provided examples inside [CI tips & tricks](https://github.com/Synthetixio/synpress#ci-tips--tricks) section.

Also, make sure you're on latest `@synthetixio/synpress@3.2.0`.

In details your setup is probably missing `xvfb` and window manager dependencies.

If you're still going to encounter this issue, please re-open.

Thanks,
Jakub.
