### ISSUE TITLE
The browser keeps reconnecting while running synpress via docker image

### ISSUE THREAD

**Issue by mp-dthr** [Synthetixio/synpress#602]
When running synpress via docker image in the pipeline (headless mode), the browser keeps disconnecting and reconnecting.
It sometimes causes some steps to be executed twice in a row when there is actually only one step in the test/code.
I guess allocating more resources to the container could solve the problem, but we are pretty limited for pipeline execution (2 CPUs). We tried increasing the default command timeout to 20 seconds, but it didn't help.

Do you have any other suggestions on what we could try?

**Comment by drptbl** [comment]
Hey @mp-dthr,

Sorry for inconvenience.

Can you try again with `@synthetixio/synpress@3.1.0` and report back?

This issue should be fixed now.

Also, if you're using `docker-e2e`, I suggest to update to one of these:
```
- synthetixio/docker-e2e:14.21-debian
- synthetixio/docker-e2e:16.19-debian
- synthetixio/docker-e2e:18.13-debian
```
or..
```
- synthetixio/docker-e2e:14.21-ubuntu
- synthetixio/docker-e2e:16.19-ubuntu
- synthetixio/docker-e2e:18.13-ubuntu
```

Thanks,
Jakub.

**Comment by drptbl** [comment]
Hey, this should not be a case anymore.

Please use provided examples inside [CI tips & tricks](https://github.com/Synthetixio/synpress#ci-tips--tricks) section.

Also, make sure you're on latest `@synthetixio/synpress@3.2.0`.

In details your setup is probably missing `xvfb` and window manager dependencies.

If you're still going to encounter this issue, please re-open.

Thanks,
Jakub.
