### ISSUE TITLE
Metamask notification does not appear when calling "confirmMetamaskPermissionToSpend()"

### ISSUE THREAD

**Issue by burasov-artyom** [Synthetixio/synpress#607]
Hello. I ran into a problem that when "confirmMetamaskPermissionToSpend()" is called, one notification hangs in Metamask, but nothing happens and the function fails when the wait ends.

I saw that there were messages with similar ones, only called by the "confirmMetamaskTransaction ()" function:
https://github.com/Synthetixio/synpress/issues/592
https://github.com/Synthetixio/synpress/issues/601

**Comment by drptbl** [comment]
Hey @burasov-artyom @ChrisChan888,

Sorry for inconvenience.

Can you try again with `@synthetixio/synpress@3.1.0` and report back?

This issue should be fixed now.

Thanks,
Jakub.

**Comment by mp-dthr** [comment]
Hi,
I didn't have this problem with synpress 3.0.1, but when I upgraded to 3.1.0, I now see this problem.
A notification window is displayed but keeps hanging. The notification never gets confirmed.

Not sure that the locator that it is looking for is present/valid:
`waiting for locator('.notification [data-testid="custom-spending-cap-input"]') to be visible
`

<img width="441" alt="Screenshot 2023-02-13 at 12 34 00" src="https://user-images.githubusercontent.com/114396660/218448266-9f5c59b5-89f2-4f7c-ba0c-08fc06a97db5.png">

Latest Metamask version is used `10.25.0`

**Comment by drptbl** [comment]
> Hi, I didn't have this problem with synpress 3.0.1, but when I upgraded to 3.1.0, I now see this problem. A notification window is displayed but keeps hanging. The notification never gets confirmed.
> 
> Not sure that the locator that it is looking for is present/valid: `waiting for locator('.notification [data-testid="custom-spending-cap-input"]') to be visible `
> 
> <img alt="Screenshot 2023-02-13 at 12 34 00" width="441" src="https://user-images.githubusercontent.com/114396660/218448266-9f5c59b5-89f2-4f7c-ba0c-08fc06a97db5.png">
> 
> Latest Metamask version is used `10.25.0`

@mp-dthr are you able to take a screenshot of metamask notification when it hangs? thanks 🙏

**Comment by mp-dthr** [comment]
Here it is:
<img width="1713" alt="Screenshot 2023-02-13 at 12 49 46" src="https://user-images.githubusercontent.com/114396660/218451282-d0541e60-c27d-4b6e-acc3-c96dffd2dd13.png">

And this is the notification in the expanded view:
<img width="1728" alt="Screenshot 2023-02-13 at 12 53 54" src="https://user-images.githubusercontent.com/114396660/218451328-c32c9f8f-2f2b-41bc-a688-e824b292ace7.png">

**Comment by drptbl** [comment]
@mp-dthr you should use `cy.confirmMetamaskTransaction()` for this notification.

**Comment by drptbl** [comment]
Hey, this should not be a case anymore.

Please use provided examples inside [CI tips & tricks](https://github.com/Synthetixio/synpress#ci-tips--tricks) section.

Also, make sure you're on latest `@synthetixio/synpress@3.2.0`.

In details your setup is probably missing `xvfb` and window manager dependencies.

If you're still going to encounter this issue, please re-open.

Thanks,
Jakub.
