### ISSUE TITLE
acceptMetamaskAccess doesn't work in CI

### ISSUE THREAD

**Issue by Cianekjr** [Synthetixio/synpress#614]
Hello,

I wrote synpress test and everything works on localhost (mac M1 - yarn test:e2e:local). But it doesn't work on mac intel and github actions. The error appears after `cy.acceptMetamaskAccess()`:

```bash
message: "Request of type 'wallet_requestPermissions' already pending for origin xyz./ Please wait.",
```

There was already an issue like that:
https://github.com/Synthetixio/synpress/issues/498
but nothing helps.

I have two github actions workflows:
1. github-actions-docker
2. github-actions-local
and both throw the same error.
I have already used docker-compose and docker-compose.ci.

There is a minimal reproduction:
https://github.com/Cianekjr/e2e

Could you take a look, please? Thanks ;)

**Comment by drptbl** [comment]
@Cianekjr thanks for report, will take a look until end of this week.

**Comment by fionnachan** [comment]
Hi @drptbl, any news? Trying to run it on github actions 🥲

**Comment by Cianekjr** [comment]
I found out that running tests in codemagic CI (probably the only one with M1 machines) works well.
There is a config:
https://github.com/Cianekjr/e2e/blob/dev/codemagic.yaml

But still would be nice to make it work in github actions ;).

**Comment by alexo382** [comment]
Just encountered the same issue when upgrading from Synpress 1.x to 3.x, would be nice to get a fix.

**Comment by drptbl** [comment]
Hey @Cianekjr @fionnachan @alexo382 @Sgoldik,

Sorry for inconvenience.

Can you try again with `@synthetixio/synpress@3.1.0` and report back?

This issue should be fixed now.

Thanks,
Jakub.

**Comment by alexo382** [comment]
> Hey @Cianekjr @fionnachan @alexo382 @Sgoldik,
> 
> Sorry for inconvenience.
> 
> Can you try again with `@synthetixio/synpress@3.1.0` and report back?
> 
> This issue should be fixed now.
> 
> Also, if you're using `docker-e2e`, I suggest to update to one of these:
> 
> ```
> - synthetixio/docker-e2e:14.21-debian
> - synthetixio/docker-e2e:16.19-debian
> - synthetixio/docker-e2e:18.13-debian
> ```
> 
> or..
> 
> ```
> - synthetixio/docker-e2e:14.21-ubuntu
> - synthetixio/docker-e2e:16.19-ubuntu
> - synthetixio/docker-e2e:18.13-ubuntu
> ```
> 
> Thanks, Jakub.

hey Jakub, thanks for the update! I still seem to be getting `locator resolved to hidden <div class="app os-linux">…</div>` on `acceptMetamaskAccess` in CI, any idea how to solve?

**Comment by drptbl** [comment]
@alexo382 thanks for reporting, any way I can reproduce this or see the code?

**Comment by alexo382** [comment]
> @alexo382 thanks for reporting, any way I can reproduce this or see the code?
> 
> also full error would be helpful, screenshots or video recording.

I created a sample repo where I reproduced the issue I posted above, please see the following links: 
https://github.com/alexo382/synpress-ci
https://github.com/alexo382/synpress-ci/actions/runs/4167336059/jobs/7212800741

let me know how it goes

**Comment by drptbl** [comment]
@alexo382 did quick investigation - no solution yet, but wanted to mention that everything runs fine in `docker-e2e`, however it seems to not work well with official cypress github actions (which you're using). I suppose it's some issue desktop emulation or headless mode (which is not supported).. I will keep investigating to fix it. In the meantime if you're in hurry, I advice to switch to use `docker-e2e`, you can find example implementation here and it gives you more benefits in terms of debugging and more in overall (check readme):
https://github.com/drptbl/synpress-ci/tree/a224165bb9c77f6d2d4d9c61843329e70e337ede

passing CI with `docker-e2e`:
https://github.com/drptbl/synpress-ci/actions/runs/4168005214
https://github.com/drptbl/synpress-ci/actions/runs/4168005214/jobs/7214278794
https://github.com/drptbl/synpress-ci/suites/10956391312/artifacts/554586371

will continue investigating, will keep you updated.

**Comment by alexo382** [comment]
> @alexo382 did quick investigation - no solution yet, but wanted to mention that everything runs fine in `docker-e2e`, however it seems to not work well with official cypress github actions (which you're using). I suppose it's some issue desktop emulation or headless mode (which is not supported).. I will keep investigating to fix it. In the meantime if you're in hurry, I advice to switch to use `docker-e2e`, you can find example implementation here and it gives you more benefits in terms of debugging and more in overall (check readme): https://github.com/drptbl/synpress-ci/tree/a224165bb9c77f6d2d4d9c61843329e70e337ede
> 
> passing CI with `docker-e2e`: https://github.com/drptbl/synpress-ci/actions/runs/4168005214 https://github.com/drptbl/synpress-ci/actions/runs/4168005214/jobs/7214278794 https://github.com/drptbl/synpress-ci/suites/10956391312/artifacts/554586371
> 
> will continue investigating, will keep you updated.

I just tried using `docker-e2e` and it works, but it takes around 35 minutes to run all our tests as we have over 100 and looking to add more :(. on the other hand, using the official cypress github action with parallel containers takes around 14-15 minutes instead.

let me know if you figure out the `locator resolved to hidden` issue and if I can help in any way.

**Comment by drptbl** [comment]
@alexo382 Totally understood, will keep investigating.

Keep in mind that first docker run is way slower than subsequent until everything is cached (docker layers).

Thanks,
Jakub.

**Comment by alexo382** [comment]
> @alexo382 Totally understood, will keep investigating.
> 
> Keep in mind that first docker run is way slower than subsequent until everything is cached (docker layers). Also all of this time is added for docker setup and not by making tests slower or affecting them in any way.
> 
> Thanks, Jakub.

yeah, I get that, I'm going to play around with it some more later today and see what happens. 🙏 
thanks a lot for your help and please keep us updated if you manage to fix it!

**Comment by drptbl** [comment]
cc @r3kt-eth

**Comment by tonykha123** [comment]
Hi jakub, im also getting the same issue as @alexo382 running synpress in CI it seems . Please give me a ping when you sort it out too! thank you :). tests work fine locally.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/93644855/219532619-7a9d1ac4-0922-4299-b6f2-cb8e9ec0d16f.png">

**Comment by drptbl** [comment]
@alexo382 @tonykha123 @Cianekjr 

Hey, this should not be a case anymore.

Please use provided examples inside [CI tips & tricks](https://github.com/Synthetixio/synpress#ci-tips--tricks) section.

Also, make sure you're on latest `@synthetixio/synpress@3.2.0`.

In details your setup is probably missing `xvfb` and window manager dependencies.

If you're still going to encounter this issue, please re-open.

Thanks,
Jakub.

**Comment by sebastiendan** [comment]
I have this problem today, with `3.7.0`, but it seems inconsistent in appearance (re-running the action sometimes fixes the problem).

**Comment by sebastiendan** [comment]
Is it possible to use the `docker-e2e` when using synpress as a plugin for cypress? The documentation isn't really clear as to what is needed (I see I need to add the same `docker-compose` file than the one used for synpress e2e tests, which comes with new specific env variables).
