### ISSUE TITLE
Does Synpress support RainbowKit?

### ISSUE THREAD

**Issue by Eveelin** [Synthetixio/synpress#631]
Is there any chance to reach RainbowKit's modal which is opening on connect button click? 
https://www.rainbowkit.com/
![image](https://user-images.githubusercontent.com/50451046/216536189-f162195a-8d49-457d-bb5d-1186d4c05522.png)

**Comment by drptbl** [comment]
Hi @Eveelin.

This question is related to cypress itself and how to interact with elements, not synpress technical issue.

It supports any interactions with websites.

Here's an answer:
```
cy.get('[data-testid="rk-wallet-option-metaMask"]').click();
```
