### ISSUE TITLE
Can't run Synpress with Playwright with docker

### ISSUE THREAD

**Issue by giapt** [Synthetixio/synpress#755]
I follow [this issue](https://github.com/Synthetixio/synpress/issues/742) to setup playwright+ synpress to run with docker in server Ubuntu 20, but still can't run `metamask.acceptAccess`

```
synpress  |
synpress  |   1) [chromium] › connect-wallet.spec.ts:12:5 › connect wallet using default metamask account ──────
synpress  |
synpress  |     Error: [switchToMetamaskNotification] Max amount of retries to switch to metamask notification window has been reached. It was never found.
synpress  |
synpress  |       20 |     .click();
synpress  |       21 |   await page.getByRole('button', { name: 'Confirm' }).click();
synpress  |     > 22 |   await metamask.acceptAccess({ allAccounts: false, signInSignature: true });
synpress  |          |   ^
``` 

My project : https://github.com/giapt/metamask-test

What can I do

**Comment by cuongpo** [comment]
![Screen Shot 2023-05-15 at 22 34 52](https://github.com/Synthetixio/synpress/assets/61429471/63183932-4a1a-4b20-b71e-cccb620b2d7f)
I clone your repo - and it seem work - can you try reinstall dependencies and chrome driver again ?

**Comment by giapt** [comment]
Thanks, @cuongpo , it works when I run the test direct on my Macbook too, but I need to run with docker, then push to run on Jenkin ci/cd server
Error display when run with docker
![](https://i.imgur.com/B6LKky8.png)

**Comment by drptbl** [comment]
Hey @giapt,
You either have to run your browser in headless mode or follow these docs:
https://playwright.dev/docs/next/ci#running-headed
Use `xvfb-run` to emulate desktop (because you're running browser in headful mode without desktop emulation).

I'm closing this issue as it's related to playwright itself, not synpress.

Thanks,
Jakub.
