### ISSUE TITLE
Can't use confirmDataSignatureRequest 

### ISSUE THREAD

**Issue by giapt** [Synthetixio/synpress#760]
**Describe the bug**
I use `confirmDataSignatureRequest` to confirm a transaction, but it can't
Error display :
```
waiting for locator('.notification [data-testid="signature-sign-button"]') to be visible
    ============================================================

    > 74 |     await metamask.confirmDataSignatureRequest();
```

**To Reproduce**
1. Clone this [repo](https://github.com/giapt/metamask-test)
2. Run `npx playwright test tests/test-mint-nft.spec.ts`
3. See the error

**Related repository**
[Link to repository related with this issue.](https://github.com/giapt/metamask-test)

**Expected behavior**
Confirm a transaction success

**Screenshots**
![](https://i.imgur.com/Swiq00K.png)
![](https://i.imgur.com/uVt5fC6.png)
![](https://i.imgur.com/5vSqzJC.png)

**Desktop (please complete the following information):**
 - OS: Macbook pro M1
 - Synpress version: 3.6.4
 - Metamask version : 10.25.0

**Additional context**
I check inspect then see button confirm is 
```
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Confirm</button>
```
not `data-testid="signature-sign-button"` current waiting for locator ?

**Comment by juantor16** [comment]
@giapt I cannot access the repo you shared thus being unable to reproduce the issue, do any of the buttons in this page open up the same pop up? https://metamask.github.io/test-dapp/

**Comment by giapt** [comment]
@juantor16 I pushed the repo again.
I fixed it temporarily with 
```
const notificationPage = await playwright.switchToMetamaskNotification();
const confirm_button = notificationPage.getByText("Confirm");
await confirm_button.click();
```
There seems to be no such popup in Metamask test-dapp

**Comment by YakovL** [comment]
Please check if the patch in #828 helps and comment there

**Comment by duckception** [comment]
Hey @giapt!

I cannot reproduce the issue on your repo since the dapp is not available anymore but based on the context I believe you used the wrong function. To **confirm transactions** you should be using the `.confirmTransaction()` function. 

The function `.confirmDataSignatureRequest()` that you mentioned is used for signing data. See [this comment](https://github.com/Synthetixio/synpress/pull/828#issuecomment-1714249373) for detailed usage 🫡

**Comment by giapt** [comment]
Oh, I used the wrong function, with `.confirmTransaction()`, it works perfectly
Problem is resolved
