### ISSUE TITLE
Can't use synpress with custom chain

### ISSUE THREAD

**Issue by georgi-l95** [Synthetixio/synpress#764]
**Describe the bug**
I'm trying to setup a test, while using custom chain not present here: https://github.com/wagmi-dev/references/tree/main/packages/chains#chains
This flow was working prior version 3.0.5.

**To Reproduce**
1. Create some simple test and add following network in `.env` file.
```
HEDERA_NETWORK={"0.testnet.hedera.com:50211":"0.0.3"}
OPERATOR_ID_MAIN=0.0.1322
OPERATOR_KEY_MAIN=302e020100300506032b6570042204206bb5ca5c9a33b8a12e2d962fe14587fa40e92306e9c39bcd2bb62951100d7248
CHAIN_ID=0x128
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com
MIRROR_NODE_URL_WEB3=https://testnet.mirrornode.hedera.com
LOCAL_NODE=true
SERVER_PORT=7546
# cypress metamask config
NETWORK_NAME='local hedera'
RPC_URL='http://localhost:7546'
SYMBOL='HBAR'
IS_TESTNET=true
PRIVATE_KEY='0xb46751179bc8aa9e129d34463e46cd924055112eb30b31637b5081b56ad96129'
RECEIVER_PRIVATE_KEY='0x484961ec6c67c270dc5659ea8bb61489967c6acc574d81b1e046e072d5d2436d'
STABLE_MODE=true
```
2. Or use the tests from [this](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/dapp-example) repo, but bump the version of synpress before that.

**Related repository**
https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/dapp-example

**Expected behavior**
To be able to run with chain not present in the wagmi repo.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Synpress version: All versions after 3.1.0 . Last working version is 3.0.5
- CI platform (if applicable): GitHub Actions

**Additional context**

**Comment by drptbl** [comment]
> 2\. this

Thanks for reporting! Will take a look in to this asap.

**Comment by sloonzz** [comment]
Can confirm this happens to me too. I checked the logic of the package and it seems like the `addNetwork` command from `metamask.js` is the culprit. `setupMetamask` seems to pass in the `network` as a string instead of an object. Then inside `initialSetup`, `module.exports.addNetwork` actually receives a string network instead of an object.

**Comment by georgi-l95** [comment]
Nice catch @sloonzz . Are you aware of any workaround for the time being ?

**Comment by sloonzz** [comment]
> Nice catch @sloonzz . Are you aware of any workaround for the time being ?

Currently trying to manually `setupMetamask` and `addMetamaskNetwork` but having trouble with using env variables for some reason.

**Comment by georgi-l95** [comment]
That's what I though as well, but it again gave me error that it couldn't get the network, when I tried it.

**Comment by sloonzz** [comment]
@georgi-l95 You can use my fork in the meantime. Haven't tested it yet because power went out. But I tested an earlier iteration of this and seems to work fine. https://github.com/sloonzz/synpress

**Comment by YakovL** [comment]
@georgi-l95 what error do you get? Is it the one below?

> tasksetupMetamask, Object{5}
> CypressError
> Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.
> 
> The command that returned the promise was:
> 
>   > cy.task()
> 
> The cy command you invoked inside the promise was:
> 
>   > cy.then()
> 
> Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
> 
> Cypress will resolve your command with whatever the final Cypress command yields.
> 
> The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving. [Learn more](https://on.cypress.io/returning-promise-and-commands-in-another-command)

I'm asking because it seems that I've run into the same issue, but I'm not quite sure yet. My test env is:
```
NETWORK_NAME='Mumbai'
# NETWORK_NAME=polygonMumbai
SECRET_WORDS='spell rally panda picture extra expect arch pond middle eyebrow indicate segment'
CHAIN_ID=80001
RPC_URL='https://matic-mumbai.chainstacklabs.com'
SYMBOL="MATIC"
IS_TESTNET=true
```
The only issue that I've found mentioning this error is #417, but that one is about watch mode, while I'm having troubles with the ordinary mode.

**Comment by YakovL** [comment]
I've take several steps further, and added some debugging into synpress/commands/metamask.js → initialSetup:
```
  async initialSetup(
    playwrightInstance,
    {
      secretWordsOrPrivateKey,
      network,
      password,
      enableAdvancedSettings,
      enableExperimentalSettings,
    },
  ) {
    console.log(`YL debug point 1, process.env.NETWORK_NAME is ${process.env.NETWORK_NAME}`)
    const isCustomNetwork =
      (process.env.NETWORK_NAME &&
        process.env.RPC_URL &&
        process.env.CHAIN_ID &&
        process.env.SYMBOL) ||
      typeof network == 'object';
    console.log(`YL debug point 1.1: isCustomNetwork is ${isCustomNetwork}`)
```
Suprisingly, it reports that `process.env.NETWORK_NAME` is `undefined`. Any idea how comes (it is set in .env)? Is it true in your case?

**Comment by georgi-l95** [comment]
Hey @r3kt-eth, just to confirm that latest version is working now. Thank you!
