### ISSUE TITLE
[🐛 Bug]: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by josadcha** [Synthetixio/synpress#874]
### 🔎 Have you searched existing issues to avoid duplicates?

- [X] I have made sure that my issue is not a duplicate.

### 🧪 Have you tested your code using latest version of Synpress?

- [X] I have made sure that my issue still exists on [latest version of Synpress](https://github.com/Synthetixio/synpress/releases).

### 💡 Are you able to provide enough information to be able to reproduce your issue locally?

- [X] I can provide enough details to reproduce my issue on local environment.

### Synpress version

3.7.2-beta.7

### Node.js version

18.17.1

### Operating system

Ventura 13

### Run mode

Synpress (standalone)

### CI platform (if applicable)

-

### Are you running your tests inside docker? (if applicable)

- [ ] This issue could be related to docker.

### What happened?

3 weeks ago same synpress tests were compiling correctly with `synpress 3.5.1`. Then the error mentioned in https://github.com/Synthetixio/synpress/issues/853 appeared. After upgrading to `3.7.2-beta.7` which contains the fix I started to experience a new issue:
```
Oops...we found an error preparing this test file:

  > tests/e2e/support.js

The error was:

Error: Webpack Compilation Error
/Users/julia/work/stack/maple-stack/modules/maple-webapp/node_modules/@testing-library/dom/dist/queries/role.js 172:112
Module parse failed: Unexpected token (172:112)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }
|       if (valueText !== undefined) {
>         valueMatches && (valueMatches = (0, _allUtils.matches)((0, _roleHelpers.computeAriaValueText)(element) ?? null, element, valueText, text => text));
|       }
|       return valueMatches;
``` 
project contains support.js file with default `import '@synthetixio/synpress/support/index`

could you please take a look at this new loaders issue?

### How to reproduce the bug.

The project uses vite, you can find some configuration files [here](https://gist.github.com/josadcha/c2d36dbb26c68986997d8afa6d70e862)

although worth noting that with the same setup synpress was compiling

**Comment by duckception** [comment]
Hey! 

I'm not sure this is related to Synpress since the issue is thrown by Webpack having an issue with `@testing-library/dom` package which is a dependency of `@testing-library/cypress` which then is our dependency.  

I know that your repository is private but if you could provide a minimal reproduction repo with this issue, I'm down to look around and see whether we can fix this by bumping some dependencies on our side. 

Not sure how else I can help with this one 🥲

**Comment by josadcha** [comment]
hello @duckception , thank you for quick response!

Actually you're right, the issue is in a wrong subdependency version of `@testing-library/dom`, probably there were duplicates in yarn.lock

a workaround is to add a resolution in `package.json` to use the version listed in `@testing-library/cypress`:

```json
"resolutions": {
    "@testing-library/dom": "^8.1.0"
  }
```

**Comment by ppasta90** [comment]
hello, i have the same problem and tried the solution provided by @josadcha but the problem persists. Here's my package.json

`{
  "name": "mm-dapp-react",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "lint": "eslint .",
    "lint:fix": "npm run lint --fix"
  },
  "dependencies": {
    "@metamask/detect-provider": "^2.0.0",
    "@synthetixio/synpress": "^3.7.2-beta.9",
    "env-cmd": "^10.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.44.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-unused-imports": "^3.0.0",
    "typescript": "^5.1.6",
    "vite": "^4.4.3",
    "vite-tsconfig-paths": "^4.2.0"
  }
}
`
i don't understand where to find "the version listed in @testing-library/cypress"

thanks :)
