### ISSUE TITLE
can't run with playwright

### ISSUE THREAD

**Issue by baixiaoyu2997** [Synthetixio/synpress#969]
### 🔎 Have you searched existing issues to avoid duplicates?

- [X] I have made sure that my issue is not a duplicate.

### 🧪 Have you tested your code using latest version of Synpress?

- [X] I have made sure that my issue still exists on [latest version of Synpress](https://github.com/Synthetixio/synpress/releases).

### 💡 Are you able to provide enough information to be able to reproduce your issue locally?

- [X] I can provide enough details to reproduce my issue on local environment.

### Synpress version

3.7.2-beta.8

### Node.js version

18.16.0

### Operating system

macos 14.0 

### Run mode

Playwright + Synpress (as plugin)

### Are you running your tests inside docker? (if applicable)

- [ ] This issue could be related to docker.

### What happened?

Test timeout of 30000ms exceeded while running "beforeEach" hook.

### How to reproduce the bug.

just use demos from `https://github.com/synpress-io/synpress-examples/tree/master/playwright`
and I did not modify the demo code, every demo has been tested and none of them can run normally.

### Relevant log output

```typescript
Test timeout of 30000ms exceeded while running "beforeEach" hook.

  2 | import * as metamask from "@synthetixio/synpress/commands/metamask";
  3 |
> 4 | test.beforeEach(async ({ page }) => {
    |      ^
  5 |   // baseUrl is set in playwright.config.ts
  6 |   await page.goto("/");
  7 | });

    at /Users/l.rain/Documents/workspace/DEMO/synpress-examples/playwright/isolated-state/tests/connect-wallet.spec.ts:4:6
```

**Comment by duckception** [comment]
I've just checked all Playwright examples and they are working fine. Not sure why you're running into any problems here.

Try these steps and let me know if you still get the error:
1. `pnpm install` in root folder, i.e., `synpress-examples`.
2. `cd playwright/isolated-state`.
3. `pnpm install`.
4. `pnpm test`.

**Comment by baixiaoyu2997** [comment]
1. `rm -rf node_modules`
2. `rm pnpm-lock.yaml`
3. `pnpm install`
4. `cd playwright/isolated-state`
5. `rm -rf node_modules`
6. `rm pnpm-lock.yaml`
7. `pnpm install`
8. `pnpm tset`

I also updated pnpm to the latest version：`8.10.0`
this time i got other error:
```
TypeError: Cannot read properties of undefined (reading 'waitForTimeout')

   at ../fixtures.ts:44

  42 |
  43 |     // setup metamask
> 44 |     await initialSetup(chromium, {
     |     ^
  45 |       secretWordsOrPrivateKey:
  46 |         "test test test test test test test test test test test junk",
  47 |       network: "optimism",

    at Object.fixBlankPage (/Users/l.rain/Documents/workspace/DEMO/synpress-examples/playwright/isolated-state/node_modules/.pnpm/@synthetixio+synpress@3.7.2-beta.8_@babel+core@7.23.2_@babel+preset-env@7.23.2_babel-loader@9_sjfvea6pvrnjktb425hvxcy5ae/node_modules/@synthetixio/synpress/commands/playwright.js:399:16)
    at initialSetup (/Users/l.rain/Documents/workspace/DEMO/synpress-examples/playwright/isolated-state/node_modules/.pnpm/@synthetixio+synpress@3.7.2-beta.8_@babel+core@7.23.2_@babel+preset-env@7.23.2_babel-loader@9_sjfvea6pvrnjktb425hvxcy5ae/node_modules/@synthetixio/synpress/commands/metamask.js:1478:22)
    at Object.context (/Users/l.rain/Documents/workspace/DEMO/synpress-examples/playwright/isolated-state/fixtures.ts:44:5)
```

**Comment by baixiaoyu2997** [comment]
thanks, looking forward to the new version very much
